yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='home'),
    path('follow/', views.follow_index, name='follow_index'),
    path('group/<slug:slug>/edit/', views.group_edit, name='group_edit'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/follow/', views.profile_follow,
         name='profile_follow'),
    path('profile/<str:username>/unfollow/', views.profile_unfollow,
         name='profile_unfollow'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/comment/', views.add_comment,
         name='add_comment'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/delete/', views.post_delete, name='post_delete'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/group/', views.group_create, name='group_create'),
    path('create/', views.post_create, name='post_create'),
]

yatube/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeView,
                                       PasswordChangeDoneView,
                                       PasswordResetView,
                                       PasswordResetDoneView,
                                       PasswordResetConfirmView,
                                       PasswordResetCompleteView)
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('logout/', LogoutView.as_view(template_name='users/logged_out.html'),
         name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'),
        name='password_reset_complete'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(template_name='users/password_change.html'),
        name='password_change'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'),
        name='password_reset_done'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(template_name='users/password_reset.html'),
        name='password_reset'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'),
        name='password_change_done'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/templates/includes/block.html
{% load thumbnail %}
<article>
    <ul>
        {% if not no_author %}
            <li>
                Автор: {{ post.author.get_full_name  }}
                <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
            </li>
        {% endif %}
        <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
{% endthumbnail %}
<p>{{ post.text }}</p>
<a href="{% url 'posts:post_detail' post.pk %}">Подробная информация</a>
{% if post.group and not is_group_page  %}
    <br>
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы "{{ post.group.title }}"</a>
{% endif %}
</article>
{% if not forloop.last %}<hr>{% endif %}

yatube/templates/includes/comment.html
{% load user_filters %}
{% if user.is_authenticated %}
    <div class="card my-4">
        <h5 class="card-header">Добавить комментарий:</h5>
        <div class="card-body">
            <form method="post" action="{% url 'posts:add_comment' post.id %}">
                {% csrf_token %}
                <div class="form-group mb-12">
                    {{ form.text|addclass:"form-control" }}
                    <small id="{{ form.text.id_for_label }}-help" class="form-text text-muted">{{ form.text.help_text|safe }}</small>
                </div>
                <button type="submit" class="btn btn-primary">Отправить</button>
            </form>
        </div>
    </div>
{% endif %}
{% for comment in comments %}
    <div class="media mb-4">
        <div class="media-body">
            <h5 class="mt-0">
                <a href="{% url 'posts:profile' comment.author.username %}">{{ comment.author.username }}</a>
            </h5>
            <p>{{ comment.text }}</p>
        </div>
    </div>
{% endfor %}

yatube/templates/includes/form.html
<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">{{ form_name }}</div>
            <div class="card-body">
                {% load user_filters %}
                {# Загружаем фильтры #}
                {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}<div class="alert alert-danger">{{ error|escape }}</div>{% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}<div class="alert alert-danger">{{ error|escape }}</div>{% endfor %}
                {% endif %}
                <form method="post" action='' %}">
                    {% csrf_token %}
                    {# Выводим поля в цикле, по отдельности #}
                    {% for field in form %}
                        <div class="form-group row my-3">
                            <label for="{{ field.id_for_label }}">
                                {{ field.label }}
                                {% if field.field.required %}<span class="required text-danger">*</span>{% endif %}
                            </label>
                            {# К полю ввода добавляем атрибут class #}
                            {{ field|addclass:'form-control' }}
                            {% if field.help_text %}
                                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                            {% endif %}
                        </div>
                    {% endfor %}
                    {% if is_button %}
                        <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-primary">{{ button_name }}</button>
                        </div>
                    {% endif %}
                </form>
            </div>
            <!-- card body -->
        </div>
        <!-- card -->
    </div>
    <!-- col -->
</div>
<!-- row -->

yatube/templates/includes/header.html
{% load static %}
<header>
    <nav class="navbar navbar-light" style="background-color: lightskyblue">
      <div class="container">
        <a class="navbar-brand" href="{% url 'posts:home' %}">
          <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
          <span style="color:red">Ya</span>tube
        </a>
        {# Добавлено в спринте #}
  
        {% comment %}
        Меню - список пунктов со стандартными классами Bootsrap.
        Класс nav-pills нужен для выделения активных пунктов 
        {% endcomment %}
        {% with request.resolver_match.view_name as view_name %}  
        <ul class="nav nav-pills">
          <li class="nav-item"> 
            <a class="nav-link {% if view_name  == 'about:author' %} active {% endif %}" 
                href="{% url 'about:author' %}">Об авторе
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name  == 'about:tech' %} active {% endif %}" 
                href="{% url 'about:tech' %}">Технологии
            </a>
          </li>
          {% if perms.posts.add_groups %}
          <li class="nav-item"> 
            <a class="nav-link{% if view_name  == 'posts:group_create' %} active {% endif %}"
              href="{% url 'posts:group_create' %}">Новая группа
            </a>
          </li>
          {% endif %}
          {% if request.user.is_authenticated %}
          <li class="nav-item"> 
            <a class="nav-link{% if view_name  == 'posts:post_create' %} active {% endif %}"
              href="{% url 'posts:post_create' %}">Новая запись
            </a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link link-light {% if view_name  == 'users:password_change' %} active {% endif %}"
              href="{% url 'users:password_change' %}">Изменить пароль
            </a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link link-light" href="{% url 'users:logout' %}">Выйти</a>
          </li>
          <li>
            Пользователь: {{ user.username }}
          </li>
          {% else %}
          <li class="nav-item"> 
            <a class="nav-link link-light {% if view_name  == 'users:login' %} active {% endif %}"
                href="{% url 'users:login' %}">Войти
            </a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link link-light {% if view_name  == 'users:signup' %} active {% endif %}" 
              href="{% url 'users:signup' %}">Регистрация
            </a>
          </li>
          {% endif %}
        </ul>
        {% endwith %} 
        {# Конец добавленого в спринте 4 #}
      </div>
    </nav>      
  </header>

yatube/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
    <nav aria-label="Page navigation" class="my-5">
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1">Первая</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
                </li>
            {% endif %}
            {% for i in page_obj.paginator.page_range %}
                {% if page_obj.number == i %}
                    <li class="page-item active">
                        <span class="page-link">{{ i }}</span>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                    </li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">Следующая</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Последняя</a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endif %}

yatube/templates/includes/switcher.html
{% if user.is_authenticated %}
    <div class="row my-3">
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link {% if index %}active{% endif %}"
                   href="{% url 'posts:home' %}">Все авторы</a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if follow %}active{% endif %}"
                   href="{% url 'posts:follow_index' %}">Избранные авторы</a>
            </li>
        </ul>
    </div>
{% endif %}