yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='home'),
    path('follow/', views.follow_index, name='follow_index'),
    path('group/<slug:slug>/edit/', views.group_edit, name='group_edit'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/follow/', views.profile_follow,
         name='profile_follow'),
    path('profile/<str:username>/unfollow/', views.profile_unfollow,
         name='profile_unfollow'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/comment/', views.add_comment,
         name='add_comment'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/delete/', views.post_delete, name='post_delete'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/group/', views.group_create, name='group_create'),
    path('create/', views.post_create, name='post_create'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200,
                             verbose_name='Название группы')
    slug = models.SlugField(unique=True,
                            verbose_name='slug-код группы')
    description = models.TextField(verbose_name='Описание группы')

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'
        permissions = (("add_groups", "Может добавлять группы"),)

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(verbose_name='Текст поста',
                            help_text='Введите текст поста')
    pub_date = models.DateTimeField(auto_now_add=True,
                                    verbose_name='Дата публикации')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор поста'
    )
    group = models.ForeignKey(Group, on_delete=models.SET_NULL,
                              blank=True, null=True,
                              verbose_name='Група поста',
                              help_text=('Группа, к которой будет'
                                         ' относиться пост'),
                              related_name='posts')
    image = models.ImageField(
        verbose_name='Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        ordering = ['-pub_date']

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        verbose_name='Пост для комментирования',
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор комментария'
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Введите текст комментария'
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации',
    )

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор поста'
    )

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'
        constraints = [
            models.UniqueConstraint(fields=['user', 'author'],
                                    name='unique_follow'),
        ]

yatube/posts/forms.py
from django import forms
from .models import Post, Group, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image', )
        help_texts = {'text': 'Текст нового поста',
                      'group': 'Группа, к которой будет относиться пост'}


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ('title', 'slug', 'description', )
        help_texts = {'title': 'Короткое название',
                      'slug': 'slug-строка, которая может быть частью адреса',
                      'description': 'Полное описание группы'}


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import CommentForm, GroupForm, PostForm
from .models import Comment, Follow, Group, Post, User
from .utils import my_paginator


@cache_page(settings.CACHE_TIME)
def index(request):
    posts = Post.objects.all()
    page_number = request.GET.get('page')
    page_obj = my_paginator(posts, page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.select_related("author").all()
    page_number = request.GET.get('page')
    page_obj = my_paginator(posts, page_number)
    context = {
        'group': group,
        'page_obj': page_obj,
        'is_group_page': True,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    user = get_object_or_404(User, username=username)
    posts = user.posts.select_related("group").all()
    page_number = request.GET.get('page')
    page_obj = my_paginator(posts, page_number)
    if request.user.is_authenticated:
        following = Follow.objects.filter(
            user=request.user).filter(author=user).exists()
    else:
        following = False
    context = {
        'page_obj': page_obj,
        'no_author': True,
        'author': user,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    num_posts = Post.objects.filter(author=post.author).count()
    comments = Comment.objects.select_related(
        "author").select_related("post").filter(post=post)
    form = CommentForm()
    context = {
        'post': post,
        'num_posts': num_posts,
        'id': post_id,
        'comments': comments,
        'form': form,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', post.author.username)
    context = {
        'form': form,
        'title': 'Добавить запись',
        'button_name': 'Добавить',
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect("posts:post_detail", post_id)
    form = PostForm(request.POST or None,
                    files=request.FILES or None, instance=post)
    if form.is_valid():
        form.save()
        return redirect("posts:post_detail", post_id)
    context = {
        'form': form,
        'title': 'Редактировать запись',
        'button_name': 'Сохранить',
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_delete(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author.username != request.user.username:
        return redirect("posts:post_detail", post_id)
    post.delete()
    return redirect('posts:profile', post.author.username)


@permission_required('posts.add_groups')
def group_create(request):
    form = GroupForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('posts:group_list', form.cleaned_data['slug'])
    context = {
        'form': form,
        'title': 'Добавить группу',
        'button_name': 'Добавить',
    }
    return render(request, 'posts/create_post.html', context)


@permission_required('posts.add_groups')
def group_edit(request, slug):
    group = get_object_or_404(Group, slug=slug)
    form = GroupForm(request.POST or None, instance=group)
    if form.is_valid():
        form.save()
        return redirect("posts:group_list", slug)
    context = {
        'form': form,
        'title': 'Редактировать группу',
        'button_name': 'Сохранить',
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    followers = Follow.objects.filter(user=request.user)
    posts = Post.objects.filter(
        author__in=followers.values("author")
    )
    page_number = request.GET.get('page')
    page_obj = my_paginator(posts, page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    if ((not Follow.objects.filter(user=user).filter(
         author=author).exists()) and (author != user)):
        follower = Follow()
        follower.author = author
        follower.user = user
        follower.save()
    return redirect('posts:profile', author.username)


@login_required
def profile_unfollow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    follower = Follow.objects.filter(user=user).filter(author=author)
    if follower.exists():
        follower.delete()
    return redirect('posts:profile', author.username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block content %}
    {% load user_filters %}
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-md-8 p-5">
                <div class="card">
                    <div class="card-header">{{ title }}</div>
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group row my-3"
                                     {% if field.field.required %} aria-required="true" {% else %} aria-required="false" {% endif %}>
                                    <label for="{{ field.id_for_label }}">
                                        {{ field.label }}
                                        {% if field.field.required %}<span class="required text-danger">*</span>{% endif %}
                                    </label>
                                    <div>
                                        {{ field|addclass:'form-control' }}
                                        {% if field.help_text %}
                                            <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                                        {% endif %}
                                    </div>
                                </div>
                            {% endfor %}
                            <div class="d-flex justify-content-end">
                                <button type="submit" class="btn btn-primary">{{ button_name }}</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block title %}{{ title }}{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h1>Посты подписок</h1>
        {% with follow=True %}
            {% include 'includes/switcher.html' %}
        {% endwith %}
        {% for post in page_obj %}
            {% include 'includes/block.html' %}
        {% endfor %}
        {% include 'includes/paginator.html' %}
    </div>
{% endblock %}
{% block title %}Посты подписок{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h1>{{ group.title }}</h1>
        <p>{{ group.description }}</p>
        {% for post in page_obj %}
            {% include 'includes/block.html' %}
        {% endfor %}
        {% include 'includes/paginator.html' %}
    </div>
{% endblock %}
{% block title %}Записи группы {{ group.title }}{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h1>Последние обновления на сайте</h1>
        {% with index=True %}
            {% include 'includes/switcher.html' %}
        {% endwith %}
        {% for post in page_obj %}
            {% include 'includes/block.html' %}
        {% endfor %}
        {% include 'includes/paginator.html' %}
    </div>
{% endblock %}
{% block title %}Последние обновления на сайте{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load static %}
{% load user_filters %}
{% block content %}
    <div class="container py-5">
        <div class="row">
            <aside class="col-12 col-md-3">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
                    <li class="list-group-item">
                        Группа: {{ post.group.title }}
                        {% if post.group %}
                            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
                        {% endif %}
                    </li>
                    <li class="list-group-item">Автор: {{ post.author.get_full_name  }} {{ post.author.username }}</li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        Всего постов автора:  <span >{{ num_posts }}</span>
                    </li>
                    <li class="list-group-item">
                        <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
                    </li>
                </ul>
            </aside>
            <article class="col-12 col-md-9">
                {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            <p>{{ post.text }}</p>
            {% if request.user == post.author %}
                <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">редактировать запись</a>
                <br>
                <label>
                    <input type="checkbox" id="protect" onchange="button_enable();">
                    вы хотите удалить запись?
                </label>
                <br>
                <a class="btn btn-primary"
                   href="{% url 'posts:post_delete' post.pk %}"
                   hidden
                   id="delete_button">Удалить запись</a>
                <script src="{% static 'js/confirm_delete.js' %}"></script>
            {% endif %}
        </article>
        {% include  'includes/comment.html' %}
    </div>
</div>
{% endblock %}
{% block title %}Пост  {{ post.text }}{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <div class="mb-5">
            <h1>{{ author.get_full_name }}</h1>
            <h3>Всего постов: {{ page_obj.paginator.count }}</h3>
            {% if request.user.is_authenticated and request.user != author %}
                {% if following %}
                    <a class="btn btn-lg btn-light"
                       href="{% url 'posts:profile_unfollow' author.username %}"
                       role="button">Отписаться</a>
                {% else %}
                    <a class="btn btn-lg btn-primary"
                       href="{% url 'posts:profile_follow' author.username %}"
                       role="button">Подписаться</a>
                {% endif %}
            {% endif %}
        </div>
        {% for post in page_obj %}
            {% include 'includes/block.html' %}
        {% endfor %}
        {% include 'includes/paginator.html' %}
    </div>
{% endblock %}
{% block title %}профайл пользователя {{ usermodel.get_full_name }}{% endblock %}