yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeView,
                                       PasswordChangeDoneView,
                                       PasswordResetView,
                                       PasswordResetDoneView,
                                       PasswordResetConfirmView,
                                       PasswordResetCompleteView)
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('logout/', LogoutView.as_view(template_name='users/logged_out.html'),
         name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'),
        name='password_reset_complete'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(template_name='users/password_change.html'),
        name='password_change'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'),
        name='password_reset_done'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(template_name='users/password_reset.html'),
        name='password_reset'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'),
        name='password_change_done'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


#  создадим собственный класс для формы регистрации
#  сделаем его наследником предустановленного класса UserCreationForm
class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        # укажем модель, с которой связана создаваемая форма
        model = User
        # укажем, какие поля должны быть видны в форме и в каком порядке
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/users/views.py
from django.views.generic import CreateView

# Функция reverse_lazy позволяет получить URL по параметрам функции path()
# Берём, тоже пригодится
from django.urls import reverse_lazy

# Импортируем класс формы, чтобы сослаться на неё во view-классе
from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    # После успешной регистрации перенаправляем пользователя на главную.
    success_url = reverse_lazy('posts:home')
    template_name = 'users/signup.html'

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
    <div class="row justify-content-center">
        <div class="col-md-8 p-5">
            <div class="card">
                <div class="card-header">Выход</div>
                <div class="card-body">
                    <p>Вы вышли из своей учётной записи. Ждём вас снова!</p>
                </div>
                <!-- card body -->
            </div>
            <!-- card -->
        </div>
        <!-- col -->
    </div>
    <!-- row -->
{% endblock %}

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
    {% load user_filters %}
    <div class="row justify-content-center">
        <div class="col-md-8 p-5">
            <div class="card">
                <div class="card-header">Войти на сайт</div>
                <div class="card-body">
                    {% if form.errors %}
                        {% for field in form %}
                            {% for error in field.errors %}<div class="alert alert-danger">{{ error|escape }}</div>{% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}<div class="alert alert-danger">{{ error|escape }}</div>{% endfor %}
                    {% endif %}
                    <form method="post"
                          {% if action_url %} action="{% url action_url %}" {% endif %}>
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group row my-3"
                                 {% if field.field.required %} aria-required="true" {% else %} aria-required="false" {% endif %}>
                                <label for="{{ field.id_for_label }}">
                                    {{ field.label }}
                                    {% if field.field.required %}<span class="required text-danger">*</span>{% endif %}
                                </label>
                                <div>
                                    {{ field|addclass:'form-control' }}
                                    {% if field.help_text %}
                                        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                                    {% endif %}
                                </div>
                            </div>
                        {% endfor %}
                        <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-primary">Войти</button>
                            <a href="{% url 'users:password_reset' %}" class="btn btn-link">Забыли пароль?</a>
                        </div>
                    </form>
                </div>
                <!-- card body -->
            </div>
            <!-- card -->
        </div>
        <!-- col -->
    </div>
    <!-- row -->
{% endblock %}

yatube/templates/users/password_change.html
{% extends "base.html" %}
{% block title %}Изменение пароля{% endblock %}
{% block content %}
    {% load user_filters %}
    {% with form_name='Изменение пароля' %}
        {% with button_name='Изменить пароль' %}
            {% with is_button=True %}
                {% include "includes/form.html" %}
            {% endwith %}
        {% endwith %}
    {% endwith %}
{% endblock %}

yatube/templates/users/password_change_done.html
{% extends "base.html" %}
{% block title %}Пароль изменён{% endblock %}
{% block content %}
    {% with form_name='Пароль изменён' %}
        {% with is_button=False %}
            {% include "includes/form.html" %}
        {% endwith %}
    {% endwith %}
{% endblock %}

yatube/templates/users/password_reset.html
{% extends "base.html" %}
{% block title %}Восстановление пароля{% endblock %}
{% block content %}
    {% load user_filters %}
    {% with form_name='Восстановление пароля' %}
        {% with button_name='Восстановить пароль' %}
            {% with is_button=True %}
                {% include "includes/form.html" %}
            {% endwith %}
        {% endwith %}
    {% endwith %}
{% endblock %}

yatube/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% block title %}Пароль изменён{% endblock %}
{% block content %}
    {% with form_name='Пароль изменён' %}
        {% with is_button=false %}
            {% with is_button=False %}
                {% include "includes/form.html" %}
            {% endwith %}
        {% endwith %}
    {% endwith %}
{% endblock %}

yatube/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}Восстановление пароля{% endblock %}
{% block content %}
    {% load user_filters %}
    {% if validlink %}
        {% with form_name='Восстановление пароля' %}
            {% with button_name='Сохранить пароль' %}
                {% with is_button=True %}
                    {% include "includes/form.html" %}
                {% endwith %}
            {% endwith %}
        {% endwith %}
    {% else %}
        <div class="row justify-content-center">
            <div class="col-md-8 p-5">
                <div class="card">
                    <div class="card-header">Ошибка</div>
                    <div class="card-body">
                        <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
                    </div>
                    <!-- card body -->
                </div>
                <!-- card -->
            </div>
            <!-- col -->
        </div>
        <!-- row -->
    {% endif %}
{% endblock %}

yatube/templates/users/password_reset_done.html
{% extends "base.html" %}
{% block title %}Письмо с восстановлением отправлено{% endblock %}
{% block content %}
    {% with form_name='Письмо с восстановлением отправлено' %}
        {% with is_button=False %}
            {% include "includes/form.html" %}
        {% endwith %}
    {% endwith %}
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
    {% with form_name='Зарегистрироваться' %}
        {% with button_name='Зарегистрироваться' %}
            {% with is_button=True %}
                {% url 'users:signup' as commit_url %}
                {% include "includes/form.html" %}
            {% endwith %}
        {% endwith %}
    {% endwith %}
{% endblock %}